name: Atualização

on:
  push:
    paths:
      - 'datapackage.yaml'
      - 'schemas/*'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'upload/*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gabrielbdornas/dtamg:latest
    steps:
      - uses: actions/checkout@v2
      - name: Data
        run: make data
      - name: Build
        run: make build
      - name: Commit new datapackage.json
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Compare
        run: make compare
  validate:
  # this workflow will automate datapackage validation with frictionless
  # for more information see: https://repository.frictionlessdata.io/
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate data
        uses: frictionlessdata/repository@v1
  ckan:
    runs-on: ubuntu-latest
    container:
      image: gabrielbdornas/dtamg:latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Update data package to CKAN with dpckan
        env:
          CKAN_HOST: ${{ secrets.CKAN_HOST }}
          CKAN_KEY: ${{ secrets.CKAN_KEY }}
        run: dpckan --ckan-host "$CKAN_HOST" --ckan-key "$CKAN_KEY" dataset update
